.github/workflows/xpanse-website-cd.yml, .github/workflows/xpanse-website-ci.yml, README.md
fixes eclipse-xpanse/xpanse#357
=> add deployment action

package.json
fix for vulnerability raised in https://github.com/eclipse-xpanse/xpanse-website/security/dependabot/1
=> override vulnerable dependencies with new versions

docs/Contribute/calendar.mdx, docusaurus.config.js, src/css/calendar.css, src/pages/index.tsx
=> add calendar page

docs/database.md, docusaurus.config.js
fixes eclipse-xpanse/xpanse#531
fixes eclipse-xpanse/xpanse#533
=> add database documentation

docs/authentication-authorization.md, docusaurus.config.js
fixes eclipse-xpanse/xpanse#568
=> add auth documentation

docs/runtime.md, docs/service-deployment.md, docusaurus.config.js, static/xpanse-api/openapi.json
fixes eclipse-xpanse/xpanse#674
=> add service deployment doc

docs/runtime.md
fixes https://github.com/eclipse-xpanse/xpanse/issues/678
=> add documentation for proxy

docs/ui.md
fixes https://github.com/eclipse-xpanse/xpanse/issues/702
=> add documentation for ui docker

docs/authentication-authorization.md
related to eclipse-xpanse/xpanse#735
=> Rename the Role CSP to ISV

.github/workflows/xpanse-website-cd.yml, docusaurus.config.js, package-lock.json
fixes https://github.com/eclipse-xpanse/xpanse/issues/755
=> push changes to gh-pages branch

docs/plugins.md, docs/runtime.md, docusaurus.config.js, src/css/index.css, static/xpanse-api/openapi.json
Fixes https://github.com/eclipse-xpanse/xpanse/issues/835
Nav bar before -
Navbar after -
=> update api, videos and documentation

docs/runtime.md
Fixed eclipse-xpanse/xpanse#836
=> Xpanse Runtime documentation modifications

docs/authentication-authorization.md
Fixed eclipse-xpanse/xpanse#869
=> change all authorization properties to dot separated

docs/plugins.md
related to https://github.com/eclipse-xpanse/xpanse/issues/880
=> add plugin vars doc

docs/database.md
fixes https://github.com/eclipse-xpanse/xpanse/issues/948
=> update database documentation

docs/FurtherReading/resources.md
fixes https://github.com/eclipse-xpanse/xpanse/issues/1098
=> update slide links

.github/dependabot.yml
fixes https://github.com/eclipse-xpanse/xpanse/issues/1106
=> add dependabot job

docs/ui.mdx
related to https://github.com/eclipse-xpanse/xpanse/issues/1239
=> update service worker info

docs/package-structure.mdx, docusaurus.config.ts
related to https://github.com/eclipse-xpanse/xpanse/issues/1265
=> add package structure documentation

docusaurus.config.ts
fixes https://github.com/eclipse-xpanse/xpanse/issues/1297
=> fix base url

docusaurus.config.ts
related https://github.com/eclipse-xpanse/xpanse/issues/1340
=> add algolia search for docs

docusaurus.config.ts, package-lock.json, package.json
related https://github.com/eclipse-xpanse/xpanse/issues/1340
=> use lunr local search

docs/ui.mdx
related to https://github.com/eclipse-xpanse/xpanse/issues/2123
=> update UI doc for disabling oauth

.github/vale/styles/config/vocabularies/xpanse/accept.txt, docs/developer-setup.mdx, docs/runtime.mdx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2285
=> extend developer initial setup documentation

docs/senstive-data.mdx
related to https://github.com/eclipse-xpanse/xpanse/issues/2358
=> add sensitive data documentation

docs/developer-setup.mdx, docs/webhooks.mdx
fixes https://github.com/eclipse-xpanse/xpanse/issues/2384
=> add HMAC docs for webhooks

docs/architecture.mdx, docs/developer-setup.mdx, docs/observability.mdx, docs/service-deployment.mdx, docs/spring-profiles.mdx, docs/webhooks.mdx
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2390
Based on https://github.com/eclipse-xpanse/terra-boot/pull/199
=> rename terraform-boot project to terra-boot

.github/vale/styles/config/vocabularies/xpanse/accept.txt, docs/caching.mdx, docs/developer-setup.mdx, docs/spring-profiles.mdx
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2310
Based on https://github.com/eclipse-xpanse/xpanse/pull/2451
=> add cache docs for xpanse
